language: node_js
node_js:
  - "8"
  - "10"
  - "12"

env:
  global:
    - DB2_HOST="localhost"
    - DB2_PORT=50000
    - DB2_USER="db2inst1"
    - DB2_PASSWORD="DBpa55"
    - DB2_SCHEMA="DB2INST1"

branches:
  only:
    - master
